### ISSUE TITLE
Long messages get cutoff

### ISSUE THREAD

**Issue by bicarlsen** [crabnebula-dev/devtools#319]
Long messages get cutoff with no way to expand them.
![error](https://github.com/crabnebula-dev/devtools/assets/4098092/5448b959-e411-4d1a-a935-64120eb2fe44)

**Comment by johann-crabnebula** [comment]
Thanks for reporting!

We are aware of this. You should be able to see the full content by hovering. We know this is not ideal since you will not be able to copy the full message.

We are currently working on a solution here:

#313 

The PR is still in review but should soon make it possible to copy and expand this information properly :)

**Comment by johann-crabnebula** [comment]
Update to Web DevTools is merged now.

You should be able to expand and copy longer messages now.  For messages with linebreaks and tabs there is also a formatting option.

**Comment by bicarlsen** [comment]
I just tried, and now the messages are blank.
![Screenshot from 2024-07-02 11-13-52](https://github.com/crabnebula-dev/devtools/assets/4098092/4d54a189-e6ef-435b-bda4-1193fd3e2a53)

**Comment by johann-crabnebula** [comment]
Ah I see this does not look good on your end,
but we made the decision to by default hide what we refer to as "attributes". You can toggle them back on in the top right:

<img width="1489" alt="Screenshot 2024-07-02 at 20 06 19" src="https://github.com/crabnebula-dev/devtools/assets/119593300/eb5ddca8-53a9-4a42-822c-24de5b40b3d4">

**Comment by johann-crabnebula** [comment]
Does the message above work our for you @bicarlsen ?

**Comment by bicarlsen** [comment]
Yep! That was it. Thanks so much for the quick responses.
